Append tooltip to the closest positioned ancestor of the selection
estevanmaito/sharect pull request #2
Opened 2017-04-21 15:07 UTC by Laurian

Simple fix for #1, does not take into consideration nested positioned ancestors.

2017-04-21 15:22 UTC, Laurian commented on dist/sharect.babel.js
> +    function offsetParent(el) {
This is basically https://api.jquery.com/offsetParent/ from https://github.com/jquery/jquery/blob/56136897f241db22560b58c3518578ca1453d5c7/src/offset.js#L162-L172

2017-04-21 15:24 UTC, Laurian commented on dist/sharect.babel.js
> +      if (hasSelection()) {
If selection's offsetParent is not `document.body`, adjust left and top positions with offsetParent positions

2017-04-21 15:25 UTC, Laurian commented on dist/sharect.babel.js
> +      if (hasSelection()) {
Appen tooltip to body or to nearest offsetParent() of selection; that makes the positioning simpler and with no need of adjusting it on scroll

2017-04-21 15:26 UTC, Laurian commented on dist/sharect.babel.js
> +        tooltip.remove();
If the selection is in a part of the page that has different offsetParent(), kill the tooltip and recreate.

2017-04-22 15:23 UTC, estevanmaito commented on src/sharect.js
> +      var offsetParent = el.offsetParent
Use let instead of var

2017-04-22 15:28 UTC, estevanmaito commented on src/sharect.js
> +                  ? ` ${_twitterConfig.username} ${encodeURIComponent(window.location.href)}`
Don't do unrelated changes. It has nothing to do with the tooltip position.

2017-04-22 15:50 UTC, estevanmaito commented on src/sharect.js
> +        offsetParent(_selection.anchorNode.parentElement).appendChild(div)
This is the only line needed here.
`drawTooltip` is called after a `hasSelection` test in the `mouseup` event, so no need to test again here.
`offsetParent` already returns the `offsetParent || document.body`

2017-04-22 16:06 UTC, estevanmaito commented on src/sharect.js
>        function hasTooltipDrawn() {
Avoid side effects.
This function should return just `true` or `false`. If DOM manipulation or any other change is needed, it should be done outside of this function.
The `mouseup` event already tests for tooltip drawn and if it has selection. Maybe you could add another test there to look at its `offsetParent`.

2017-04-22 16:11 UTC, estevanmaito requested changes
Thanks for your time!
I really appreciate your changes. I've just added some comments along the modifications in the src code. Please, take a look.

2017-04-22 18:16 UTC, Laurian commented on src/sharect.js
> +                  ? ` ${_twitterConfig.username} ${encodeURIComponent(window.location.href)}`
true, slipped in as I needed it, will revert it in my branch

2017-04-22 18:17 UTC, Laurian commented
OK, I will do the changes, I might also fix the calculation of the position if there are nested positioned ancestors, the current fix deals with one only.

2018-10-07 00:06 UTC, estevanmaito commented
Even though mispositioned tooltip is an issue inside nested elements, it's an edge case that has never become an issue, even more than a year after the library launch.
Besides that, the changes asked weren't made, and it still doesn't solve the problem of nested elements.

2018-10-07 00:06 UTC, closed without merging